[package]
name = "corundum"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]
links = "helix_runtime"

[dependencies]
corundum_jit = { path = "corundum_jit" }
corundum_ruby = { path = "corundum_ruby" }
helix = "0.7.5"
